version: '3.8'

services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: lms_db
      POSTGRES_USER: lms_user
      POSTGRES_PASSWORD: secure-database-password
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  backend:
    build: ./backend
    command: gunicorn --bind 0.0.0.0:8000 lms_api.wsgi:application
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    environment:
      - SECRET_KEY=your-very-secure-production-secret-key
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1,your-ec2-public-ip,your-domain.com
      - DB_NAME=lms_db
      - DB_USER=lms_user
      - DB_PASSWORD=secure-database-password
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped

  celery:
    build: ./backend
    command: celery -A lms_api worker --loglevel=info
    environment:
      - SECRET_KEY=your-very-secure-production-secret-key
      - DEBUG=False
      - DB_NAME=lms_db
      - DB_USER=lms_user
      - DB_PASSWORD=secure-database-password
      - DB_HOST=db
      - DB_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - backend
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data:
  static_volume:
  media_volume:
