# Generated by Django 4.2.7 on 2025-10-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_fine_borrow_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fine',
            name='borrow_record',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fine_record', to='core.borrowrecord'),
        ),
    ]
